#! /bin/bash


    #printf("\n-i: The IP address of the server you are connecting to\n");
    #printf("-p: The port of the server you are connecting to\n");
    #printf("-c(default=1): The number of socket connections you want to send messages from\n");
    #printf("-m(default=1): The number of messages that are sent per request\n");
    #printf("-d(default=0): Time to delay in milliseconds after each request\n");
    #printf("-n: The number of requests you want to send per socket in total\n");
    #printf("-t(default=test): The name of the test files to be read (If -t test is used then it will read from test0.txt, test1.txt, etc. depending on the value of the -c argument");  
    #printf("-v: Run the program in verbose mode\n");
    #printf("-h: Displays this message\n");



strace -s 10000 -f -v -o output.txt -e trace=network ./client-5204 $*
./redooutput
./checkoutput
